version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/:/var/log/nginx/

  php:
    build: ./images/php
    volumes:
      - ./www:/var/www

  master:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    user: "1000:50"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql-master:/var/lib/mysql
      - ./etc/mysql/conf.d/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./init_data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: social
      MYSQL_ROOT_PASSWORD: test

  slave:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    user: "1000:50"
    volumes:
      - ./data/mysql-slave:/var/lib/mysql
      - ./etc/mysql/conf.d/slave.cnf:/etc/mysql/conf.d/slave.cnf
      - ./init_data:/docker-entrypoint-initdb.d
      - ./promote.sh:/tmp/promote.sh
    environment:
      - "MYSQL_DATABASE=social"
      - "MYSQL_SLAVE_PASSWORD=test"
      - "MYSQL_MASTER_PASSWORD=test"
      - "MYSQL_ROOT_PASSWORD=test"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"

  serf:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    user: "1000:50"
    volumes:
      - ./data/mysql-serf:/var/lib/mysql
      - ./etc/mysql/conf.d/serf.cnf:/etc/mysql/conf.d/serf.cnf
      - ./init_data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: social
      MYSQL_ROOT_PASSWORD: test

  mysqlconfigure:
    image: mysql:5.7
    environment:
      - "MYSQL_SLAVE_PASSWORD=test"
      - "MYSQL_MASTER_PASSWORD=test"
      - "MYSQL_ROOT_PASSWORD=test"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    volumes:
      - ./replication.sh:/tmp/replication.sh
    command: /bin/bash -x /tmp/replication.sh
