---
- name: Installing apt git
  apt:
    name: "git"
    state: latest
  tags: apt

- name: Clone repo
  git:
    repo: "{{ repository }}"
    dest: "{{ site_root }}"
    update: no
  when: "'prod' in group_names"
  tags: repo

- name: Git pull origin master
  git:
    repo: "{{ repository }}"
    dest: "{{ site_root }}"
    update: yes
    force: yes
    version: 'master'
  when: "'prod' in group_names"
  tags: ['never', 'git_pull', 'deploy']
