dev:
	ansible-playbook -i inventory.ini site.yml -l weblocal
devrep:
	ansible-playbook -i inventory.ini replica.yml -l replocal
prod:
	ansible-playbook -i inventory.ini site.yml -l webjino
prodrep:
	ansible-playbook -i inventory.ini replica.yml -l repjino
