Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.define "weblocal", primary: true do |weblocal|
    weblocal.vm.hostname = "weblocal"
    weblocal.vm.network "private_network", ip: "192.168.35.12"
    weblocal.vm.synced_folder "../www", "/var/www"
#    weblocal.vm.provision "ansible_local" do |ansible|
#      ansible.playbook = "site.yml"
#      ansible.verbose = 'v'
#    end
  end
  config.vm.define "replocal" do |replocal|
    replocal.vm.hostname = "replocal"
    replocal.vm.network "private_network", ip: "192.168.35.13"
#    replocal.vm.provision "ansible_local" do |ansible|#
#      ansible.playbook = "replica.yml"
#    end
  end
end
